md F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#149 | move F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\challenge_149_start_file.yxmd  F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#149 | ren  F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#149\challenge_149_start_file.yxmd david_149.yxmd
md F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#150 | move F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\challenge_150_start_file.yxmd  F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#150 | ren  F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#150\challenge_150_start_file.yxmd david_150.yxmd
md F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#151 | move F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\challenge_151_start_file.yxmd  F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#151 | ren  F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#151\challenge_151_start_file.yxmd david_151.yxmd
md F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#152 | move F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\challenge_152_start_file.yxmd  F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#152 | ren  F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#152\challenge_152_start_file.yxmd david_152.yxmd
md F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#153 | move F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\challenge_153_start_file.yxmd  F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#153 | ren  F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#153\challenge_153_start_file.yxmd david_153.yxmd
md F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#154 | move F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\challenge_154_start_file.yxmd  F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#154 | ren  F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#154\challenge_154_start_file.yxmd david_154.yxmd
md F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#155 | move F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\challenge_155_start_file.yxzp  F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#155 | ren  F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#155\challenge_155_start_file.yxzp david_155.yxzp
md F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#156 | move F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\challenge_156_start_file.yxzp  F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#156 | ren  F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#156\challenge_156_start_file.yxzp david_156.yxzp
md F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#157 | move F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\challenge_157_start_file.yxzp  F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#157 | ren  F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#157\challenge_157_start_file.yxzp david_157.yxzp
md F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#158 | move F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\challenge_158_start_file.yxzp  F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#158 | ren  F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#158\challenge_158_start_file.yxzp david_158.yxzp
md F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#159 | move F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\challenge_159_start_file.yxzp  F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#159 | ren  F:\Dropbox\DataSchool\Training\Alteryx-Weekly-Challenge\todo\Challenge#159\challenge_159_start_file.yxzp david_159.yxzp
pause
